# Generated by Django 5.1 on 2024-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(db_column='Emp Name', max_length=50)),
                ('emp_mob', models.CharField(db_column='Emp Mobile', max_length=11)),
                ('emp_email', models.EmailField(db_column='Email', max_length=35)),
                ('emp_paw', models.CharField(db_column='Password', max_length=50)),
                ('emp_dob', models.DateField(db_column='Date of Birth')),
                ('emp_address', models.CharField(db_column='Address', max_length=100)),
                ('emp_dept', models.CharField(db_column='Department', max_length=30)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
